### PR TITLE
Fix missing withApollo

### LINKED ISSUE #7: Two default exports in profile page
There are two default exports in the same file, so build fails because of that.
[here](https://github.com/Thinkmill/meetup-alternative/blob/master/site/pages/profile.js#L10) and [here](https://github.com/Thinkmill/meetup-alternative/blob/master/site/pages/profile.js#L191)

### LINKED ISSUE #8: Build fails
`yarn build` fails with an error `Error occurred prerendering /profile: TypeError: Cannot read property 'name' of undefined`
Temporary fixed by adding `if (!user) return 'No user'` before `user.name` statements. There is no profile link in the menu anyway.

### PR DESCRIPTION
**Pull request by w01fgang**
There was missing `withApollo` HOC and call of `ctx.apolloClient.query` inside `getInitialProps` was failing.
Also, `authenticatedUser` query was failing because `access` inside `schema.js` returned an object instead of boolean.

closes #7 
closes #8

### CODE REVIEW

File: site/pages/profile.js [hunk 1]
```diff
@@ -24,15 +25,25 @@ export default class ProfilePage extends Component {
       };
     } catch (error) {
       // If there was an error, we need to pass it down so the page can handle it.
+      console.log('error', error);
```
Comment (MadeByMike) [inline site/pages/profile.js]:
```suggestion
```

**Review by MadeByMike — APPROVED** [review]
